support WDL's `runtime.disks` using fixed values #95
common-workflow-lab/wdl-cwl-translator pull request #100
Opened 2021-10-31 17:42 UTC by RaOneG

1. Changed `disks` entry in [`CollectQualityYieldMetrics`](https://github.com/RaOneG/wdl-cwl-translator/blob/main/wdl2cwl/tests/wdl_files/CollectQualityYieldMetrics.wdl) to [`disks: 40`](https://github.com/RaOneG/wdl-cwl-translator/blob/ad7c5239e158fabff68de65f75a30e1be468cdcc/wdl2cwl/tests/wdl_files/CollectQualityYieldMetrics.wdl#L41)
2. Commented out all other `disks` entries in other [wdl_files](https://github.com/RaOneG/wdl-cwl-translator/tree/main/wdl2cwl/tests/wdl_files)
```
$ git grep disks: -- wdl2cwl/tests/wdl_files/
wdl2cwl/tests/wdl_files/CollectQualityYieldMetrics.wdl:    disks: 40
wdl2cwl/tests/wdl_files/CollectReadgroupBamQualityMetrics.wdl:    #disks: "local-disk " + disk_size + " HDD"
wdl2cwl/tests/wdl_files/TrimAdapters.wdl:    #disks: "local-disk ${disk} HDD"
wdl2cwl/tests/wdl_files/UmiCorrection.wdl:        #disks: "local-disk ${disk} HDD"
wdl2cwl/tests/wdl_files/read_string_cornercase.wdl:        #disks: "local-disk ${required_disk} HDD"
wdl2cwl/tests/wdl_files/validateOptimus_1.wdl:        #disks: "local-disk ${required_disk} HDD"
wdl2cwl/tests/wdl_files/validateOptimus_2.wdl:       #disks: "local-disk ${required_disk} HDD"
wdl2cwl/tests/wdl_files/validateOptimus_3.wdl:        #disks: "local-disk ${required_disk} HDD"
wdl2cwl/tests/wdl_files/validateOptimus_4.wdl:        #disks: "local-disk ${required_disk} HDD"
wdl2cwl/tests/wdl_files/validateOptimus_5.wdl:    #disks: "local-disk ${required_disk} HDD"
```
3. Generated a CWL object to support `runtime.disks` to CWL conversion `outdirMin`
https://github.com/RaOneG/wdl-cwl-translator/blob/ad7c5239e158fabff68de65f75a30e1be468cdcc/wdl2cwl/main.py#L646-L671

2021-10-31 17:47 UTC, RaOneG commented
This fixes issue #95

2021-10-31 19:11 UTC, mr-c requested changes
I think too much got added to this PR. Please review https://github.com/common-workflow-lab/wdl-cwl-translator/pull/100/files and adjust your PR to only include the relevant files and changes

2021-11-01 00:28 UTC, RaOneG commented
> I think too much got added to this PR. Please review https://github.com/common-workflow-lab/wdl-cwl-translator/pull/100/files and adjust your PR to only include the relevant files and changes

I removed the irrelevant files :)

2021-11-01 07:56 UTC, mr-c commented
Thanks @RaOneG ! Next I'll wait to see what the continuous integration tests report

2021-11-02 07:20 UTC, mr-c commented
I edited the PR description to contain the phrase `fix #95` as per https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

2021-11-03 17:18 UTC, RaOneG commented
``

> I edited the PR description to contain the phrase `fix #95` as per https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

Hey @mr-c,
I adjusted some of [`main.py`](https://github.com/common-workflow-lab/wdl-cwl-translator/blob/a78cec084c852c19322e632cdda6c31dce1ee9db/wdl2cwl/main.py) code and the CI tests are not coming back with results, could there be a problem?

2021-11-03 18:09 UTC, mr-c commented
> Hey @mr-c, I adjusted some of [`main.py`](https://github.com/common-workflow-lab/wdl-cwl-translator/blob/a78cec084c852c19322e632cdda6c31dce1ee9db/wdl2cwl/main.py) code and the CI tests are not coming back with results, could there be a problem?

For security reasons I have to approve running the tests every time a new contributor pushes (nothing personal!). Feel free to run the tests locally via `tox` as well

2021-11-04 05:43 UTC, RaOneG commented
Hey @mr-c,

Wouldn't disk entry in the WDL file need to have a unit according to the [mapping](https://github.com/dnanexus/dxCompiler/blob/main/doc/CWL_v1.2.0_to_WDL_v1.md#:~:text=though%20the%20values%20will%20need%20to%20be%20converted%20from%20MiB%20to%20GiB%20(the%20latter%20two%20are%20conventions%20in%20WDL%201.0%20and%20specifications%20in%202.0))? or do I assume it is always going to be in `GiB`?

For now, I modified the `disks` entry in `CollectQualityYieldMetrics` to [`disks: "40 GiB"`](https://github.com/common-workflow-lab/wdl-cwl-translator/blob/4179602662e742f9acbb4dec7e41dd753027c8b9/wdl2cwl/tests/wdl_files/CollectQualityYieldMetrics.wdl#L41)
I tested it locally and all tests passed with `make test` and `tox`.

2021-11-04 07:23 UTC, mr-c commented on .gitignore
> +rammin.py*
?

2021-11-04 13:18 UTC, RaOneG commented
It is weird how it didn't pass the tests when it passed them locally. Any insight? @mr-c 
```
$ make test
cd wdl2cwl/tests && cwltest --tool cwltool --test cwl_tests.yaml
Test [1/3] validateOptimus_2
Test [2/3] CollectQualityYieldMetrics
Test [3/3] bcftools_stats
All tests passed
pytest
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /media/raoneg/DATA/Courses+Camps/Outreachy/CWL/wdl-cwl-translator, configfile: tox.ini
plugins: cov-3.0.0, forked-1.3.0, xdist-2.4.0
gw0 [62] / gw1 [62] / gw2 [62] / gw3 [62]
..............................................................           [100%]
============================== 62 passed in 3.36s ==============================
```

2021-11-04 13:41 UTC, mr-c requested changes
Please remove `.coverage` and `coverage.xml` from this PR

2021-11-04 16:18 UTC, mr-c requested changes
For fixed values, a plain number (interpreted as being in `GiB`) is also valid. Can you add that?

https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#disks

Likewise a quoted number (`"40"`) without a suffix.

If there is no `disks` specification, then we should assume the CWL equivalent of `1 GiB`

2021-11-04 16:18 UTC, mr-c commented on wdl2cwl/main.py
> +        append_str = '${\nvar unit = "' + unit + '";'
This function isn't used, so you should either make use of it, or remove it

2021-11-04 16:18 UTC, mr-c commented on wdl2cwl/main.py
> +                input_name = ast.task_runtime["disks"][
Lines 697, 701, and 709 and not executed by the tests. Please either remove them or add/modify the tests so that they are used

2021-11-05 03:37 UTC, RaOneG commented
> For fixed values, a plain number (interpreted as being in `GiB`) is also valid. Can you add that?
> 
> https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#disks
> 
> Likewise a quoted number (`"40"`) without a suffix.
> 
> If there is no `disks` specification, then we should assume the CWL equivalent of `1 GiB`

Should I cover the rest of the cases? When a suffix is given or the input is a list?

2021-11-05 04:16 UTC, RaOneG commented
Okay, this is the last commit. @mr-c Could u kindly review it?

2021-11-05 08:17 UTC, mr-c commented on wdl2cwl/main.py
> +    # elif "disks" not in ast.task_runtime:
Why was this commented out? We should always have an `outdirMin` with the default value if there is no other request from the user. This is required by the OpenWDL 1.1 specifications as I mentioned previously. Yes, you will have to regenerate the other CWL descriptions to match this change.

2021-11-05 08:24 UTC, mr-c commented on wdl2cwl/tests/wdl_files/CollectReadgroupBamQualityMetrics.wdl
> +    #disks: "local-disk " + disk_size + " HDD"
```suggestion
    disks: "30"  #disks: "local-disk " + disk_size + " HDD"
```

To test the other code path for a number string

2021-11-05 11:35 UTC, mr-c requested changes

2021-11-05 11:35 UTC, mr-c commented on wdl2cwl/main.py
> +                outdirMin=outdir_min,
```suggestion
        requirements.append(
            cwl.ResourceRequirement(
                outdirMin=get_outdir_min(ast.task_runtime["disks"]),
```

Simplify

2021-11-05 11:35 UTC, mr-c commented on wdl2cwl/main.py
> +    elif "disks" not in ast.task_runtime:
```suggestion
    elif:
```
Redundant to check again here

2021-11-05 11:35 UTC, mr-c commented on wdl2cwl/main.py
> +                outdirMin=outdir_min,
```suggestion
        requirements.append(
            cwl.ResourceRequirement(
                outdirMin=get_outdir_min("1"),
```
Simplify

2021-11-05 11:58 UTC, mr-c commented on wdl2cwl/main.py
> +        )
```suggestion
    if "disks" in ast.task_runtime:
        outdir_min=get_outdir_min(ast.task_runtime["disks"])
    else:
        outdir_min=get_outdir_min("1")
    requirements.append(cwl.ResourceRequirement(outdirMin=outdir_min)
```
Further simplify

2021-11-05 12:01 UTC, mr-c commented on wdl2cwl/main.py
> +    requirements.append(cwl.ResourceRequirement(outdirMin=outdir_min)
```suggestion
    outdir_min=get_outdir_min(getattr(ast.task_runtime, "disks", "1"))
    requirements.append(cwl.ResourceRequirement(outdirMin=outdir_min))
```
Even further simplify

2021-11-05 12:11 UTC, mr-c commented
Dear @RaOneG ; I get notifications for every change in this repo. Please don't (re-)request reviews from me, that just causes extra emails and notifications. Thanks!

2021-11-05 16:22 UTC, mr-c commented
@RaOneG Please consider testing before pushing. `make format` will fix the formatting issues.

2021-11-06 04:15 UTC, RaOneG commented
I do test, but I thought the problem was [here](https://github.com/common-workflow-lab/wdl-cwl-translator/blob/fbcf91b67592ab94d71e08d2f33fc000f159655e/wdl2cwl/main.py#L654) cause it was pointing to it.

2021-11-06 09:47 UTC, mr-c approved these changes

2021-11-06 09:49 UTC, merged