add pytest
common-workflow-lab/wdl-cwl-translator pull request #11
Opened 2021-06-10 18:23 UTC by dinithiW

2021-06-14 10:12 UTC, mr-c requested changes
Can you look over https://docs.pytest.org/en/6.2.x/goodpractices.html#choosing-a-test-layout-import-rules so that you don't need to move the python files?

2021-06-14 10:16 UTC, mr-c commented
Lets name the package `wdl2cwl`

2021-06-14 10:19 UTC, mr-c commented
When you're done with the PR, I'll setup https://en.wikipedia.org/wiki/Continuous_integration with GitHub Actions to automatically run pytest on every PR after this one

2021-06-14 10:22 UTC, mr-c commented on tests/WdlV1_1.py
> +    index+=1
Move this into the `main` function. Add an argument for the file name of the input WDL file

2021-06-14 16:39 UTC, dinithiW commented
> Lets name the package `wdl2cwl` and then follow https://docs.pytest.org/en/6.2.x/goodpractices.html#tests-as-part-of-application-code

@mr-c Do we have to change the project name to wdl2cwl as well? Anyway, having the name as wdl-cwl-translator gives a syntax error when used for imports

2021-06-14 17:45 UTC, mr-c commented
> > Lets name the package `wdl2cwl` and then follow https://docs.pytest.org/en/6.2.x/goodpractices.html#tests-as-part-of-application-code
> 
> @mr-c Do we have to change the project name to wdl2cwl as well? Anyway, having the name as wdl-cwl-translator gives a syntax error when used for imports

That makes sense, the `-` will be interpreted as a minus sign. So either use `wdl_cwl_translator` or `wdl2cwl`

2021-06-15 13:17 UTC, mr-c approved these changes

2021-06-15 13:17 UTC, merged