complete the adoptation of main.py
common-workflow-lab/wdl-cwl-translator pull request #124
Opened 2022-01-16 11:47 UTC by Th3nn3ss

2022-01-16 12:20 UTC, mr-c requested changes
Great progress!

The title says complete, but I don't see a test for several files in https://github.com/common-workflow-lab/wdl-cwl-translator/blob/main/wdl2cwl/tests/wdl_files/  ~~`bowtie_2.wdl`~~, ~~`bowtie_3.wdl`~~, ~~`CollectQualityYieldMetrics.wdl`~~, `CollectReadgroupBamQualityMetrics.wdl`, ~~`read_string_cornercase.wdl`~~

Some notes from running `for file in cwl_files/*.cwl ; do meld  ${file} oop_cwl_files/$(basename ${file}) ; done` inside `wdl2cwl/tests/` follow

2022-01-16 12:20 UTC, mr-c commented on wdl2cwl/tests/oop_cwl_files/deepvariant.cwl
> +        glob: $(inputs.outputVcf + ".tbi")
```suggestion
        glob: $(inputs.outputVcf).tbi
```
As shown in the non OOP version: https://github.com/common-workflow-lab/wdl-cwl-translator/blob/729faea7fdef86b8dcd47997fe03320045d36473/wdl2cwl/tests/cwl_files/deepvariant.cwl#L64

2022-01-16 12:20 UTC, mr-c commented on wdl2cwl/tests/oop_cwl_files/minCores.cwl
> +    coresMin: $("8")
```suggestion
    coresMin: 8
```

2022-01-16 12:20 UTC, mr-c commented on wdl2cwl/tests/oop_cwl_files/vardict.cwl
> +    type: float
```suggestion
  - id: mappingQuality
    default: 20.0
    type: float
```

```suggestion
    default: 20.0
```
A YAML float, as it is `type: float`, not `type: [float, int]`

2022-01-16 12:38 UTC, Th3nn3ss commented
> Great progress!
> 
> The title says complete, but I don't see a test for several files in https://github.com/common-workflow-lab/wdl-cwl-translator/blob/main/wdl2cwl/tests/wdl_files/ `bowtie_2.wdl`, `bowtie_3.wdl`, `CollectQualityYieldMetrics.wdl`, `CollectReadgroupBamQualityMetrics.wdl`, `read_string_cornercase.wdl`
> 
> Some notes from running `for file in cwl_files/*.cwl ; do meld ${file} oop_cwl_files/$(basename ${file}) ; done` inside `wdl2cwl/tests/` follow

This was because of outdirMin that we are expected to handle after feature parrity.

2022-01-18 09:22 UTC, mr-c commented on wdl2cwl/tests/oop_cwl_files/minCores.cwl
> +    coresMin: $("8")
This is wrong because `coresMIn` is of type `long`, or `float`; or a CWL Expression that returns a `long` or `float`; but not a string :-)

2022-01-18 09:23 UTC, mr-c commented
Moved some of my requested changes to https://github.com/common-workflow-lab/wdl-cwl-translator/issues/127 ; lets fix the type mismatches I highlighted and merge!

2022-01-18 09:52 UTC, kinow approved these changes
Nothing to add besides @mr-c's comments. +1 :tada:

2022-01-18 09:52 UTC, kinow commented on wdl2cwl/tests/test_miniwdl.py
> +        ),
:train: That's a lot of workflows! Hooray! :tada:

2022-01-18 09:52 UTC, kinow commented on wdl2cwl/main_oop.py
> +        # condition to determin if the openning and closing quotes should be added to string
s/determin/determine
s/openning/opening

2022-01-18 10:33 UTC, mr-c commented on wdl2cwl/tests/oop_cwl_files/CollectReadgroupBamQualityMetrics.cwl
> +    outdirMin: '30'
```suggestion
    outdirMin: 30
```

2022-01-18 10:57 UTC, mr-c commented on wdl2cwl/tests/oop_cwl_files/CollectReadgroupBamQualityMetrics.cwl
> +            $(inputs.collect_gc_bias_metrics ? "PROGRAM="CollectGcBiasMetrics"" : "") \
```suggestion
            $(inputs.collect_gc_bias_metrics ? 'PROGRAM="CollectGcBiasMetrics"' : "") \
```
like in the original WDL https://github.com/gatk-workflows/gatk4-exome-analysis-pipeline/blob/3c43ebd645759c0895539ea4231dad13bb1ae363/tasks/Qc.wdl#L174

2022-01-18 12:20 UTC, mr-c requested changes
Sooo close!

2022-01-18 12:20 UTC, mr-c commented on wdl2cwl/tests/oop_cwl_files/CollectQualityYieldMetrics.cwl
> +    outdirMin: 40
```suggestion
    outdirMin: 40960
```
for WDL, `runtime.disks` defaults to `GiB` units if not specified

https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#disks

2022-01-18 12:20 UTC, mr-c commented on wdl2cwl/tests/oop_cwl_files/CollectReadgroupBamQualityMetrics.cwl
> +    outdirMin: 30
```suggestion
    outdirMin: 30720
```

2022-01-18 12:20 UTC, mr-c commented on wdl2cwl/tests/oop_cwl_files/CollectReadgroupBamQualityMetrics.cwl
> +            $(inputs.collect_gc_bias_metrics ? "PROGRAM='CollectGcBiasMetrics'" : "") \
```suggestion
            $(inputs.collect_gc_bias_metrics ? 'PROGRAM="CollectGcBiasMetrics"' : "") \
```
Everything inside the primary quotes goes on the command line; so changing the type of the inner quotes is problematic

2022-01-19 09:09 UTC, mr-c approved these changes

2022-01-19 09:22 UTC, merged