Size ceil functions
common-workflow-lab/wdl-cwl-translator pull request #137
Opened 2022-01-24 11:39 UTC by Th3nn3ss

closes #103 & #104 

The size function is a WDL.Expr.Apply expression that accepts two arguments, the input file name and the memory unit in Binary. 
The ceil function is a WDL.Expr.Apply expression that accepts only one argument, usually a float, and returns the upper bound of the literal. 

The javascript Math.ceil is used in the retuned cwl_expression.

2022-01-24 11:43 UTC, Th3nn3ss commented on wdl2cwl/main.py
> +            if isinstance(part, WDL.Expr.Placeholder):
only placeholders in strings have been observed. No other expression seems possible to be embedded in a string.

2022-01-24 11:58 UTC, mr-c commented on wdl2cwl/tests/cwl_files/TrimAdapters_without_comment.cwl
> +        + inputs.fastq2_input_files.size / 1024^3)) + 10) + ' HDD')
```suggestion
    outdirMin: $(Math.ceil(2*(inputs.fastq1_input_files.size / 1024^3
        + inputs.fastq2_input_files.size / 1024^3)) + 10)
```

https://www.commonwl.org/v1.2/CommandLineTool.html#ResourceRequirement  ; when we don't say explicitly, then an `expression` can return any of the other listed types: `long` or `float`, but not `string`. In fact, the concept of `local-disk` and `HDD` does not exist in CWL

Additionally, you can't nest one `$()` expression in another `$()` with duplicate `$(`; remove the inner`$( ... )`

Though, is this the right calculation? The source `disks` declaration does not include any units, so the default according to https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#disks is `GiB`

2022-01-24 12:46 UTC, mr-c requested changes
If this PR is to fix #103 and #104 then I would expect both example listed in those issues to be demonstrated here as well

2022-01-24 12:46 UTC, mr-c commented on wdl2cwl/main.py
> +                        return f"$({outdir_str}*1024)"
What if the WDL `disks` entry has used non-default units like ` disks: "local-disk ${disk} MiB" ?

2022-01-24 12:46 UTC, mr-c commented on wdl2cwl/main.py
> +                raise ValueError(f"Size unit {size_unit} not handle yet")
I get this, but it would be nicer to handle all the WDL units now https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#units-of-storage

2022-02-02 13:19 UTC, mr-c commented
superseded by #150

2022-02-02 13:19 UTC, closed without merging