Wdl meta
common-workflow-lab/wdl-cwl-translator pull request #18
Opened 2021-06-29 07:11 UTC by dinithiW

Issue warning for parameter meta and meta.
Add test case for parameter_meta.

2021-06-29 18:20 UTC, mr-c requested changes

2021-06-29 18:20 UTC, mr-c commented on wdl2cwl/tests/cwl_files/smoove.cwl
> +    entry: 'set -e mkdir -p $(inputs.outputDir) smoove call  --outdir $(inputs.outputDir)  --name
This should have been broken up into three separate lines, not smooshed all together 😃

2021-06-30 12:33 UTC, mr-c commented on wdl2cwl/tests/cwl_files/smoove.cwl
> +    entry: 'set -e mkdir -p $(inputs.outputDir) smoove call  --outdir $(inputs.outputDir)  --name
Let's do a video chat and we can debug this together

2021-06-30 18:04 UTC, dinithiW commented
The new command does not work with the input file used previously. Giving out an error
```
ERROR [job CollectQualityYieldMetrics] Job error:
("Error collecting output for parameter 'quality_yield_metrics':\nNewResult.cwl:12:5: Did not find output file with glob pattern: '['metrics_file']'", {})
WARNING [job CollectQualityYieldMetrics] completed permanentFail
{}
WARNING Final process status is permanentFail

2021-07-01 10:09 UTC, mr-c commented on wdl2cwl/main.py
>                  index += 1
I think this block is the problem, you're filtering out the trailing `\` which we want to keep
``` diff
@@ -83,12 +84,8 @@ def get_command(
 
             index = end_index + 1
         else:
-            if command[index] != "\\":
-                new_command += command[index]
-                index += 1
-            else:
-                # new_command += " "
-                index += 1
+            new_command += command[index]
+            index += 1
     return new_command
```

2021-07-01 14:10 UTC, mr-c requested changes

2021-07-01 14:10 UTC, mr-c commented on wdl2cwl/WdlV1_1ParserVisitor.py
> +            self.workflow_inputs_unbound.append([input_type, str(ctx.Identifier())])'''
```suggestion
```
Lets not commit commented out code

2021-07-01 15:57 UTC, mr-c commented on wdl2cwl/WdlV1_1ParserVisitor.py
> +        self.task_meta_check = 1
This line is never called by any of the tests. Can you either add a meta section to one of the tests, or remove this?

2021-07-02 11:11 UTC, merged