Change memory requirement
common-workflow-lab/wdl-cwl-translator pull request #35
Opened 2021-07-20 18:33 UTC by dinithiW

Add js function to handle memory requirements

2021-07-26 10:17 UTC, mr-c commented on wdl2cwl/main.py
> +        + '"].match(/[0-9]+/g));\nvar memory = "";\nif(unit==="GiB"){\n\tmemory = value*1024;\n}\nreturn memory;\n}'
Great start! Now to implement the rest of the units: https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#units-of-storage

2021-07-26 10:27 UTC, mr-c requested changes
Great start! Now to implement the rest of the units: https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#units-of-storage

2021-07-27 11:04 UTC, dinithiW commented
Add the rest of storage units for JS expressions

2021-07-27 11:11 UTC, dinithiW commented
Is it needed to round the number up in case the answer is a decimal number?

2021-07-27 16:02 UTC, mr-c commented
> Is it needed to round the number up in case the answer is a decimal number?

No rounding needed, `float`s are okay: https://www.commonwl.org/v1.2/CommandLineTool.html#ResourceRequirement

2021-07-27 16:03 UTC, mr-c approved these changes

2021-07-27 16:03 UTC, merged