Handle expression placeholders in command section
common-workflow-lab/wdl-cwl-translator pull request #55
Opened 2021-08-09 14:35 UTC by dinithiW

Handles expression placeholders with ```${}``` syntax in the command section of the WDL document.
New test case has been added.

2021-08-16 10:49 UTC, mr-c requested changes

2021-08-16 10:49 UTC, mr-c commented on wdl2cwl/tests/wdl_files/UmiCorrection.wdl
> +task CorrectUMItools {
Where is this file from?

2021-08-16 10:49 UTC, mr-c commented on wdl2cwl/main.py
> +            command[index] == "$" and command[index + 1] == "{"
Only replace `${…}` style if the command block is in the `command { ... }`style (and never if the command block is in the `command <<< >>>` style): https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#expression-placeholders

Also, don't replace if the identifier is not the name of any of the inputs.

2021-08-18 11:11 UTC, dinithiW commented
Modified code as requested

2021-08-18 11:37 UTC, merged