Handle WDL function sub()
common-workflow-lab/wdl-cwl-translator pull request #62
Opened 2021-08-12 18:08 UTC by dinithiW

Fixes #61

2021-08-16 10:27 UTC, mr-c commented on wdl2cwl/tests/cwl_files/bowtie.cwl
> +            $(inputs.sep=","readsDownstream) \
I don't think this works?

2021-08-16 10:28 UTC, mr-c commented on wdl2cwl/tests/cwl_files/bowtie.cwl
> +            $(return inputs["sub(indexFiles[0]"].replace("(\.rev)?\.[0-9]\.ebwt$","");) \
Should `sub()` still be here?

2021-08-18 15:23 UTC, dinithiW commented
Modified code as requested

2021-08-18 17:14 UTC, mr-c requested changes

2021-08-18 17:14 UTC, mr-c commented on wdl2cwl/main.py
> +                    append_str_sub = (
Great! Can we get a test case with an array of files that doesn't use `[0]`?

2021-08-18 17:46 UTC, mr-c approved these changes

2021-08-18 17:46 UTC, merged